# Name your workflow
name: daily_update

# Set on which events you want run the actions.
# In this case the workflow will run on push for master and on pull request for master and develop branches
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'matcher'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: run matcher
        run: |
          cd src
          pip install -r requirements.txt
          python main.py
          